### ISSUE TITLE
import coordinates typo?

### ISSUE THREAD

**Issue by Altoc** [SE-Team-Two/SpeakEasy#11]
Unsure if it is intentional, but in app.py we have:
`from coordinate import Coordinate`
when I believe it is supposed to be:
`from coordinates import Coordinate`
Emphasis on the plural 'coordinates'. I had to make that correction in order to get things running for myself.

**Comment by vzyrianov** [comment]
Interesting. Is it possible the file in which the Coordinate class is declared named coordinates.py for you?

Because the word that follows the keyword "from" has to be the name of the file to import from and currently the file is named coordinate.py in the repo.
