### ISSUE TITLE
Finish Creating Social Media Profiles to Advertise Service

### ISSUE THREAD

**Issue by jmc339** [SE-Team-Two/SpeakEasy#30]

**Comment by jmc339** [comment]
Twitter Account Created

**Comment by Altoc** [comment]
what is the name/handles of all the social medias again?

**Comment by jmc339** [comment]
Twitter: https://twitter.com/SpeakEasyGlobal
Facebook: https://www.facebook.com/SpeakEasyGlobal/?view_public_for=2287166178231184

The Handles for both: @SpeakEasyGlobal
