### ISSUE TITLE
Logo needs to be created

### ISSUE THREAD

**Issue by vzyrianov** [SE-Team-Two/SpeakEasy#8]

**Comment by jmc339** [comment]
Working On some Logo Ideas Now.

**Comment by jmc339** [comment]
![matt_logoidea_dancers](https://user-images.githubusercontent.com/15052231/46321710-dd277000-c5b2-11e8-8f70-820e30d56797.jpg)
![Uploading Matt_logoidea_flapper.jpg…]()

**Comment by jmc339** [comment]
![matt_logoidea_flapper](https://user-images.githubusercontent.com/15052231/46321725-ef091300-c5b2-11e8-8eed-4715804a9f12.jpg)

**Comment by Altoc** [comment]
I like them both a lot, the second one particularly
